--Xiaocheng Hou

/*
  Insert tuples to FamilyPacakge table
*/
INSERT INTO FAMILYPACKAGE VALUES (1, '23 Beacon St. Hillside IL', '708-555-9384');
INSERT INTO FAMILYPACKAGE VALUES (2, '4930 Dickens Ave Chicago IL', '312-555-9403');
INSERT INTO FAMILYPACKAGE VALUES (3, '345 Fullerton St. Chicago IL', '773-555-0032');
INSERT INTO FAMILYPACKAGE VALUES (4, '34 Maple Ln Elmhurst IL', '312-555-9382');
INSERT INTO FAMILYPACKAGE VALUES (5, '563 Harvard Ave Lisle IL', '630-555-9321');

INSERT INTO RECCENTERMEMBER VALUES (1, 'Abby', 'Smith', TO_DATE('5/21/1983','MM/DD/YYYY'), 1);
INSERT INTO RECCENTERMEMBER VALUES (2, 'Mike', 'O''Shea', TO_DATE('7/4/1968','MM/DD/YYYY'), 2);
INSERT INTO RECCENTERMEMBER VALUES (3, 'April', 'O''Shea', TO_DATE('6/23/1954','MM/DD/YYYY'), 2);
INSERT INTO RECCENTERMEMBER VALUES (4, 'Vijay', 'Gupta',TO_DATE('8/1/1945','MM/DD/YYYY'),null);
INSERT INTO RECCENTERMEMBER VALUES (5, 'Lisa', 'Tang', TO_DATE('11/5/2000','MM/DD/YYYY'), 3);
INSERT INTO RECCENTERMEMBER VALUES (6, 'Harry', 'Smith', TO_DATE('2/3/1972','MM/DD/YYYY'),null);
INSERT INTO RECCENTERMEMBER VALUES (7, 'Justin', 'Smith', TO_DATE('2/2/1983','MM/DD/YYYY'),1);
INSERT INTO RECCENTERMEMBER VALUES (8, 'Lisa', 'Brown', TO_DATE('12/28/1959','MM/DD/YYYY'),null);
INSERT INTO RECCENTERMEMBER VALUES (9, 'Harry', 'Tang', TO_DATE('4/3/1948','MM/DD/YYYY'), 3);
INSERT INTO RECCENTERMEMBER VALUES (10, 'Dongmei', 'Tang', TO_DATE('6/2/1942','MM/DD/YYYY'), 3);
INSERT INTO RECCENTERMEMBER VALUES (11, 'Laura', 'Dickinson', TO_DATE('11/11/1998','MM/DD/YYYY'),null);
INSERT INTO RECCENTERMEMBER VALUES (12, 'Victor', 'Garcia', TO_DATE('4/5/2006','MM/DD/YYYY'), 5);
INSERT INTO RECCENTERMEMBER VALUES (13, 'Emily', 'Citrin', TO_DATE('5/4/1993','MM/DD/YYYY'),null);
INSERT INTO RECCENTERMEMBER VALUES (14, 'Maria', 'Garcia', TO_DATE('7/7/2007','MM/DD/YYYY'), 5);
INSERT INTO RECCENTERMEMBER VALUES (15, 'Cassie', 'O''Shea', TO_DATE('6/2/1988','MM/DD/YYYY'), 2);
INSERT INTO RECCENTERMEMBER VALUES (16, 'Cassandra', 'McDonald', TO_DATE('7/1/1990','MM/DD/YYYY'),null);
INSERT INTO RECCENTERMEMBER VALUES (17, 'Jessie', 'Knapp', TO_DATE('9/12/1981','MM/DD/YYYY'), 4);
INSERT INTO RECCENTERMEMBER VALUES (18, 'Monica', 'Knapp', TO_DATE('9/17/1982','MM/DD/YYYY'), 4);
INSERT INTO RECCENTERMEMBER VALUES (19, 'Leslie', 'Blackburn', TO_DATE('1/19/1986','MM/DD/YYYY'), null);
INSERT INTO RECCENTERMEMBER VALUES (20, 'Sandra', 'Svoboda', TO_DATE('9/9/1999','MM/DD/YYYY'), null);
/*
UPDATE RECCENTERMEMBER
SET DOB=(SELECT TO_CHAR(dob, 'MM/DD/YYYY') FROM RECCENTERMEMBER);
*/

INSERT INTO TYPE VALUES ('Craft', 'Knitting, sewing, ect');
INSERT INTO TYPE VALUES ('Art', 'Paining, sculpting, ect');
INSERT INTO TYPE VALUES ('Exercise', 'Any courses having to do with physical activity');
INSERT INTO TYPE VALUES ('Languages', 'Anything to do with writing, literature, or communication');
INSERT INTO TYPE VALUES ('Kids', 'Courses geared towards children 13 and younger');

INSERT INTO INSTRUCTOR VALUES (1, 'Annie', 'Heard', null);
INSERT INTO INSTRUCTOR VALUES (2, 'Monica', 'Knapp', 18);
INSERT INTO INSTRUCTOR VALUES (3, 'James', 'Robertson', null);
INSERT INTO INSTRUCTOR VALUES (4, 'April', 'O’Shea', 2);
INSERT INTO INSTRUCTOR VALUES (5, 'Harry', 'Tang', 9);

INSERT INTO CLASS VALUES (1, 'Needle points', 'Craft', 2, 'SPRING', 2010);
INSERT INTO CLASS VALUES (2, 'Photography', 'Art', 1, 'FALL', 2008);
INSERT INTO CLASS VALUES (3, 'Woodworking', 'Craft', 4, 'SPRING', 2009);
INSERT INTO CLASS VALUES (4, 'Chinese (Intro.)', 'Languages', 1, 'WINTER', 2008);
INSERT INTO CLASS VALUES (5, 'Team games', 'Kids', 1, 'SUMMER', 2008);
INSERT INTO CLASS VALUES (6, 'Yoga (Intro.)', 'Exercise', 2, 'FALL', 2009);
INSERT INTO CLASS VALUES (7, 'Origami (Adv.)', 'Craft', 4, 'FALL', 2009);
INSERT INTO CLASS VALUES (8, 'Oil painting', 'Art', 3, 'SPRING', 2009);
INSERT INTO CLASS VALUES (9, 'Yoga (Adv.)', 'Exercise', 1, 'SPRING', 2008);
INSERT INTO CLASS VALUES (10, 'Chinese (Intro.)', 'Languages', 3, 'SPRING', 2009);

INSERT INTO ENROLLMENT VALUES (3, 3, 20);
INSERT INTO ENROLLMENT VALUES (1, 9, 15);
INSERT INTO ENROLLMENT VALUES (2, 9, 20);
INSERT INTO ENROLLMENT VALUES (4, 10, 30);
INSERT INTO ENROLLMENT VALUES (3, 10, 10);
INSERT INTO ENROLLMENT VALUES (5, 5, 10);
INSERT INTO ENROLLMENT VALUES (4, 9, 30);
INSERT INTO ENROLLMENT VALUES (1, 11, 25);
INSERT INTO ENROLLMENT VALUES (2, 19, 40);
INSERT INTO ENROLLMENT VALUES (7, 14, 10);
INSERT INTO ENROLLMENT VALUES (8, 12, 5);
INSERT INTO ENROLLMENT VALUES (1, 1, 30);
INSERT INTO ENROLLMENT VALUES (6, 1, 15);
INSERT INTO ENROLLMENT VALUES (9, 1, 20);
INSERT INTO ENROLLMENT VALUES (8, 1, 25);
INSERT INTO ENROLLMENT VALUES (1, 13, 18);
INSERT INTO ENROLLMENT VALUES (2, 20, 9);
INSERT INTO ENROLLMENT VALUES (10, 4, 15);
INSERT INTO ENROLLMENT VALUES (1, 2, 3);
INSERT INTO ENROLLMENT VALUES (5, 1, 16);
INSERT INTO ENROLLMENT VALUES (5, 7, 20);
INSERT INTO ENROLLMENT VALUES (4, 12, 13);
INSERT INTO ENROLLMENT VALUES (5, 14, 30);
INSERT INTO ENROLLMENT VALUES (5, 12, 35);
